FileVersion = 1

[Project]
Name = "lua53-beef"
TargetType = "BeefLib"
StartupObject = "lua53_beef.Program"
DefaultNamespace = "lua53_beef"

[Configs.Debug.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x86/lua53.dll\")"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/lua53.dll\")"]

[Configs.Debug.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/liblua53.so\")"]

[Configs.Release.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x86/lua53.dll\")"]

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/lua53.dll\")"]

[Configs.Release.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/liblua53.so\")"]

[Configs.Paranoid.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x86/lua53.dll\")"]

[Configs.Paranoid.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/lua53.dll\")"]

[Configs.Paranoid.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/liblua53.so\")"]

[Configs.Test.Win32]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x86/lua53.dll\")"]

[Configs.Test.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/lua53.dll\")"]

[Configs.Test.Linux64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/x64/liblua53.so\")"]
